const tl = gsap.timeline({defaults: {duration: 0.75, ease: "power2.in"}})
tl.fromTo('.img', {opacity: 0}, {opacity: 1, ease: "power2.out"})
tl.fromTo('.text', {opacity: 0}, {opacity: 1}, '<50%')
tl.fromTo('.container', {opacity: 0}, {opacity: 1}, '<')
tl.fromTo('.nav-container', {opacity: 0}, {opacity: 1}, '<')
tl.fromTo('.text-wrapper', {opacity: 0}, {opacity: 1}, '<')
